function render(){
  if(!state.token||!state.auth)return renderLogin();
  if(!state.data&&state.auth.mustChange!==true){app.innerHTML='<main class="login-shell"><div class="login-card"><h2>일정을 불러오는 중입니다.</h2></div></main>';refreshState(true);return;}
  if(state.auth.mustChange===true||state.modal==='changePassword'){app.innerHTML=renderModal();bindDynamicEvents();return;}

  const mineSessions=currentSessions();
  const mineBookings=currentBookings();
  let title='나의 일정 보기';
  let shownSessions=mineSessions,shownBookings=mineBookings;
  const q=state.studentQuery.trim();
  if(state.auth.role==='teacher'&&q){
    const name=resolveUnique(q,allStudents());
    if(name){title=`${name} 학생 일정`;shownSessions=sortSessions((state.data.sessions||[]).filter(s=>(s.students||[]).includes(name)));shownBookings=manualSort((state.data.manualBookings||[]).filter(b=>b.student===name));}
    else{shownSessions=[];shownBookings=[];}
  }
  const count=shownSessions.length+shownBookings.length;
  app.innerHTML=`<main class="page-shell">
    <header class="page-header"><div><p class="eyebrow">2027 제시문 면접 지도</p><h1>면접 지도 일정</h1></div><div class="header-actions">
      ${state.auth.role==='teacher'?`<button class="refresh-button" id="scheduleUploadBtn">일정 업로드</button><button class="refresh-button" id="materialUploadBtn">제시문 업로드</button><button class="refresh-button" id="roomManageBtn">특별실 관리</button><button class="refresh-button" id="historyBtn">변경 이력</button><button class="refresh-button" id="refreshBtn">일정 새로고침</button>`:''}
      <button class="refresh-button" id="logoutBtn">로그아웃</button></div></header>
    ${state.notice?`<div class="alert">${esc(state.notice)}</div>`:''}${state.error?`<div class="alert error">${esc(state.error)}</div>`:''}
    <div class="workspace-layout"><div class="main-column">
      <section class="panel schedule-toolbar"><div class="toolbar-group my-toolbar"><strong>나의 일정 보기</strong><span class="login-user-badge">${state.auth.role==='teacher'?'교사':'학생'} · ${esc(state.auth.name)}</span></div>${state.auth.role==='teacher'?`<div class="toolbar-group team-toolbar"><strong>전체·팀 일정 보기</strong><button class="small-button primary" data-view-team="all">전체 일정</button><button class="small-button" data-view-team="humanities">고려대(인문)&연세대팀</button><button class="small-button" data-view-team="natural">고려대(자연)팀</button></div>`:''}</section>
      ${state.auth.role==='teacher'?studentFinder():''}
      ${state.auth.role==='teacher'&&q&&!resolveUnique(q,allStudents())?'<div class="alert error">학생을 한 명으로 특정하지 못했습니다. 이름을 더 정확히 입력해 주세요.</div>':''}
      <section class="panel results-panel ${state.auth.role==='teacher'&&q?'student-results-panel':''}"><div class="panel-title"><h2>${esc(title)}</h2><span>${count}건</span></div><div class="card-list">${count?[...shownSessions.map(s=>sessionCard(s,true)),...shownBookings.map(b=>manualBookingCard(b))].join(''):'<div class="empty">표시할 일정이 없습니다.</div>'}</div></section>
    </div>${state.auth.role==='teacher'?roomSidebar():''}</div>
    <input id="scheduleFile" type="file" accept=".xlsx,.xls" class="hidden">
  </main>${renderModal()}`;
  bindMainEvents();
}

function studentFinder(){return `<section class="panel student-finder-panel"><div class="student-finder-head"><div><strong>학생 찾기</strong><span>학생 이름을 검색하면 해당 학생 일정만 모아서 보여줍니다.</span></div>${state.studentQuery?'<button id="clearStudentSearch" class="small-button">검색 해제</button>':''}</div><div class="student-finder-row"><div class="search-box"><span>⌕</span><input id="studentSearch" list="studentNames" value="${esc(state.studentQuery)}" placeholder="학생 이름 검색 · 예: 박예지"><datalist id="studentNames">${allStudents().map(n=>`<option value="${esc(n)}"></option>`).join('')}</datalist></div></div></section>`;}

function roomSidebar(){const date=state.usageDate||localTodayDateKey(),rooms=(state.data?.roomChoices||[]).filter(r=>r&&r!=='미정');return `<aside class="panel room-sidebar"><div class="room-sidebar-head"><div><span class="label">실별 사용 현황</span><strong>${esc(fmtDate(date))}</strong></div><div class="date-picker-wrap"><span>▣</span><input id="roomDate" type="date" min="2026-01-01" max="2026-12-31" value="${esc(date)}"></div><div class="date-nav"><button id="prevRoomDate">‹</button><button id="nextRoomDate">›</button></div></div><div class="room-grid-scroll"><div class="room-usage-grid"><div class="room-grid-head room-name-cell">실</div>${[1,2,3,4,5,6,7,8].map(p=>`<div class="room-grid-head">${p}</div>`).join('')}${rooms.map(room=>`<div class="room-row"><div class="room-name-cell">${esc(room)}</div>${[1,2,3,4,5,6,7,8].map(p=>roomCellHtml(date,p,room)).join('')}</div>`).join('')}</div></div><p class="room-note">날짜를 직접 선택할 수 있습니다. 빈 칸은 클릭해 면접을 예약할 수 있고, 직접 예약한 면접 칸은 다시 클릭해 예약을 취소할 수 있습니다.</p></aside>`;}

function roomCellHtml(date,period,room){const info=usageInfo(date,period,room);const disabled=['class','interview'].includes(info.kind)?'disabled':'';const label=info.kind==='class'?(info.short||'수업'):info.kind==='free'?'가능':'면접';const detail=info.kind==='free'?'예약':String(info.label||'').replace(/^수업 · |^면접 · |^직접 예약 · /,'');return `<button type="button" class="room-use-cell ${esc(info.kind)}" ${disabled} data-room-cell="${esc(room)}|${period}" title="${esc(info.kind==='free'?'클릭하여 면접 예약':info.label)}"><span>${esc(label)}</span><small>${esc(detail)}</small></button>`;}

function manualBookingCard(b){const studentMode=state.auth.role==='student';return `<article class="session-card manual-booking-card"><div class="session-topline"><span class="team-badge manual">직접 예약</span><div class="session-time"><button class="date-link" data-jump-date="${esc(b.dateKey)}">${esc(fmtDate(b.dateKey))}</button><span>${b.period}교시</span></div></div><div class="session-grid manual-grid"><div><span class="label">학생</span><strong>${esc(b.student)}</strong></div><div><span class="label">지도교사</span><strong>${esc(b.teacher)}</strong></div><div><span class="label">장소</span><strong>${esc(b.room)}</strong></div></div>${studentMode?'':`<div class="manual-booking-actions"><button class="small-button" data-cancel-booking="${esc(b.id)}">예약 취소</button></div>`}</article>`;}

function sessionCard(s,syncDate=false){
  const isTeacher=state.auth.role==='teacher';
  const prompt=sessionMaterials(s,'prompt')[0],solution=sessionMaterials(s,'solution')[0],refs=sessionMaterials(s,'reference'),recs=sessionMaterials(s,'recording');
  const rec=state.recorder[s.id]||{};
  const roomOptions=availableRoomsFor(s);
  const periodOptions=periodOptionsFor(s);
  const dateHtml=syncDate?`<button class="date-link" data-jump-date="${esc(dateKeyFromText(s.dateText))}">${esc(s.dateText)}</button>`:`<strong>${esc(s.dateText)}</strong>`;
  return `<article class="session-card" data-session="${esc(s.id)}"><div class="session-topline"><span class="team-badge ${esc(s.team)}">${esc(teamLabel(s.team))}</span><div class="session-time">${dateHtml}<span>${s.classPeriod?`${s.classPeriod}교시`:'교시 미정'}</span><small>${esc(s.period||'전체')}</small></div><span>${esc(s.group)}</span></div><div class="session-grid"><div><span class="label">학생</span><strong>${esc((s.students||[]).join(' · '))}</strong></div><div><span class="label">지도교사</span><strong>${esc(s.teacher)}</strong></div><div><span class="label">교시</span>${isTeacher?`<select data-period="${esc(s.id)}"><option value="">미정</option>${periodOptions.map(n=>`<option value="${n}" ${Number(s.classPeriod)===n?'selected':''}>${n}교시</option>`).join('')}</select>`:`<strong>${s.classPeriod?`${s.classPeriod}교시`:'미정'}</strong>`}</div><div><span class="label">장소</span>${isTeacher?`<select data-location="${esc(s.id)}" ${s.classPeriod?'':'disabled'}><option value="미정">미정</option>${roomOptions.map(r=>`<option value="${esc(r)}" ${s.location===r?'selected':''}>${esc(r)}</option>`).join('')}</select>`:`<strong>${esc(s.location||'미정')}</strong>`}</div></div><button class="prompt-button" ${prompt?'data-download-material="'+esc(prompt.id)+'"':'disabled'}><span>${esc(firstLine(s.prompt))}</span><small>${esc(secondLine(s.prompt))}</small><em class="${prompt?'prompt-ready':'prompt-missing'}">${prompt?'업로드 완료':'업로드 안 됨'}</em><b>↓</b></button>${firstLine(s.prompt).includes('고려대')?`<div class="solution-download-row"><button class="material-button solution" ${solution?'data-download-material="'+esc(solution.id)+'"':'disabled'}>해설 포함 다운로드</button><em class="${solution?'prompt-ready':'prompt-missing'}">${solution?'해설 업로드 완료':'해설 업로드 안 됨'}</em></div>`:''}${isTeacher?teacherMaterialsAndRecordings(s,refs,recs):studentRecorder(s,rec,recs)}</article>`;
}

function teacherMaterialsAndRecordings(s,refs,recs){return `<div class="material-bar"><label class="material-button upload">참고자료 올리기<input type="file" data-reference-upload="${esc(s.id)}"></label>${refs.map(m=>`<button class="material-button" data-download-material="${esc(m.id)}">${esc(m.fileName)}</button>`).join('')}</div><div class="recording-block"><div class="teacher-action-line">${(s.students||[]).map(st=>{const m=recs.find(r=>r.student===st);return `<button class="small-button ${m?'recording-ready':''}" ${m?'data-play-material="'+esc(m.id)+'"':'disabled'}>${esc(st)} 녹음 듣기${m?' · 녹음 완료':''}</button>`;}).join('')}<span class="action-spacer"></span><button class="swap-button inline-swap" data-swap="${esc(s.id)}">다른 선생님과 교환</button></div></div>`;}

function recordingRow(m,teacherMode){return `<div class="file-row"><span>${esc(m.student||'학생')} · ${esc(m.fileName)}</span><div class="inline"><button class="small-button" data-play-material="${esc(m.id)}">재생</button>${!teacherMode&&m.student===state.auth.name?`<button class="small-button" data-delete-recording="${esc(m.id)}">삭제</button>`:''}</div></div>`;}
function studentRecorder(s,rec,recs){const own=recs.filter(m=>m.student===state.auth.name),status=rec.status||'idle';let controls='';if(status==='idle')controls=`<button class="small-button" data-rec-start="${esc(s.id)}">녹음</button>`;if(status==='recording')controls=`<button class="small-button" data-rec-pause="${esc(s.id)}">일시정지</button><button class="small-button primary" data-rec-stop="${esc(s.id)}">닫기·저장 준비</button>`;if(status==='paused')controls=`<button class="small-button" data-rec-resume="${esc(s.id)}">계속</button><button class="small-button primary" data-rec-stop="${esc(s.id)}">닫기·저장 준비</button>`;if(status==='ready')controls=`<button class="small-button primary" data-rec-upload="${esc(s.id)}">닫기·저장</button><button class="small-button" data-rec-reset="${esc(s.id)}">다시 녹음</button>`;return `<div class="recording-block"><div class="recording-buttons">${controls}${own.length?`<button class="small-button" data-play-material="${esc(own[0].id)}">재생</button><button class="icon-button" data-delete-recording="${esc(own[0].id)}" title="녹음 삭제">×</button>`:''}</div>${status!=='idle'?`<div class="recorder-panel"><strong>${status==='paused'?'일시정지됨':status==='ready'?'저장 준비됨':'녹음 중'}</strong></div>`:''}${rec.url?`<audio class="audio" src="${esc(rec.url)}" controls></audio>`:''}</div>`;}
