async function startRecording(sessionId){try{const old=state.recorder[sessionId];if(old?.url){try{URL.revokeObjectURL(old.url);}catch(_){}}const stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];const media=new MediaRecorder(stream);const rec={media,stream,chunks,status:'recording',blob:null,url:'',saveOnStop:false,restartOnStop:false};state.recorder[sessionId]=rec;media.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data);};media.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());rec.blob=new Blob(chunks,{type:media.mimeType||'audio/webm'});if(rec.restartOnStop){delete state.recorder[sessionId];render();await startRecording(sessionId);return;}if(rec.url){try{URL.revokeObjectURL(rec.url);}catch(_){}}rec.url=URL.createObjectURL(rec.blob);if(rec.saveOnStop){rec.status='saving';render();await uploadRecording(sessionId);return;}rec.status='ready';render();};media.start(1000);state.error='';render();}catch(e){state.error='마이크를 사용할 수 없습니다. 브라우저의 마이크 권한을 확인해 주세요.';render();}}
function pauseRecording(id){const r=state.recorder[id];if(r?.media?.state==='recording'){r.media.pause();r.status='paused';render();}}
function resumeRecording(id){const r=state.recorder[id];if(r?.media?.state==='paused'){r.media.resume();r.status='recording';render();}}
function stopRecording(id){const r=state.recorder[id];if(r?.media&&r.media.state!=='inactive'){r.saveOnStop=true;r.restartOnStop=false;r.media.stop();}}
function restartRecording(id){const r=state.recorder[id];if(!r){void startRecording(id);return;}if(r.media&&r.media.state!=='inactive'){r.saveOnStop=false;r.restartOnStop=true;r.media.stop();return;}resetRecording(id);void startRecording(id);}
function resetRecording(id){const r=state.recorder[id];if(r?.url){try{URL.revokeObjectURL(r.url);}catch(_){}}if(r?.stream)r.stream.getTracks().forEach(t=>t.stop());delete state.recorder[id];render();}
async function uploadRecording(id){const r=state.recorder[id];if(!r?.blob)return;state.busy='recording-upload';try{state.notice='녹음을 업로드하는 중입니다.';state.error='';render();const base64=await blobToBase64(r.blob);const ext=r.blob.type.includes('ogg')?'ogg':r.blob.type.includes('mp4')?'m4a':'webm';await apiCall('uploadRecording',{token:state.token,sessionId:id,fileName:`${state.auth.name}_${dateKeyFromText(state.data.sessions.find(s=>s.id===id)?.dateText||'')}.${ext}`,mimeType:r.blob.type||'audio/webm',base64},120000);resetRecording(id);state.notice='녹음이 저장되었습니다. 담당 교사 화면에도 반영됩니다.';await refreshState(true);}catch(e){r.status='ready';state.error=e.message;state.notice='녹음 저장에 실패했습니다. 저장 다시 시도를 눌러 주세요.';render();}finally{state.busy='';}}

async function uploadMaterialZip(){const kind=qs('#materialKind').value,team=qs('#materialTeam').value,file=qs('#materialFile').files?.[0];if(!file)return;if(file.size>30*1024*1024){qs('#materialProgress').textContent='ZIP 파일은 30MB 이하로 올려 주세요.';return;}state.busy='material-upload';try{qs('#uploadMaterialNow').disabled=true;qs('#materialProgress').textContent='파일 읽는 중...';const base64=await blobToBase64(file);qs('#materialProgress').textContent='서버에 업로드 중...';const res=await apiCall('uploadMaterialZip',{token:state.token,kind,team,fileName:file.name,base64},150000);qs('#materialProgress').textContent=`업로드 완료${res.pdfCount?` · PDF ${res.pdfCount}개`:''}`;state.notice='면접 자료를 업로드했습니다.';await refreshState(false);setTimeout(()=>{state.modal=null;state.modalData=null;render();},500);}catch(e){qs('#materialProgress').textContent=e.message;}finally{state.busy='';if(qs('#uploadMaterialNow'))qs('#uploadMaterialNow').disabled=false;}}

function roomCellAction(btn){const [room,p]=btn.dataset.roomCell.split('|'),period=Number(p),date=state.usageDate||localTodayDateKey(),info=usageInfo(date,period,room);if(info.kind==='free'){state.error='';state.modal='booking';state.modalData={dateKey:date,period,room};render();}else if(info.kind==='manual'){state.error='';state.modal='booking';state.modalData={dateKey:date,period,room,booking:info.booking};render();}}
async function saveBookingFromModal(){const d=state.modalData||{},student=qs('#bookingStudent')?.value.trim();if(!student){state.error='면접 학생 이름을 입력해 주세요.';return render();}state.busy='booking-save';try{qs('#saveBookingNow').disabled=true;const res=await apiCall('createManualBooking',{token:state.token,dateKey:d.dateKey,period:Number(d.period),room:d.room,student});if(state.data){const rows=Array.isArray(res.bookings)?res.bookings:[...(state.data.manualBookings||[]).filter(x=>x.id!==res.booking?.id),...(res.booking?[res.booking]:[])];state.data.manualBookings=manualSort(rows);}state.usageDate=d.dateKey;state.notice=`${fmtDate(d.dateKey)} ${d.period}교시 ${d.room} 면접을 예약했습니다.`;state.modal=null;state.modalData=null;state.error='';render();await refreshState(false);render();}catch(e){state.error=e.message;render();}finally{state.busy='';}}
async function cancelBookingFromModal(){const b=state.modalData?.booking;if(!b)return;state.busy='booking-cancel';try{const res=await apiCall('cancelManualBooking',{token:state.token,id:b.id});if(state.data)state.data.manualBookings=Array.isArray(res.bookings)?manualSort(res.bookings):(state.data.manualBookings||[]).filter(x=>x.id!==b.id);state.notice='면접 예약을 취소했습니다.';state.modal=null;state.modalData=null;state.error='';render();await refreshState(false);render();}catch(e){state.error=e.message;render();}finally{state.busy='';}}
async function cancelBookingById(id){const b=(state.data?.manualBookings||[]).find(x=>x.id===id);if(!b)return;if(!confirm(`${fmtDate(b.dateKey)} ${b.period}교시 ${b.room} · ${b.student}\n예약을 취소할까요?`))return;state.busy='booking-cancel';try{const res=await apiCall('cancelManualBooking',{token:state.token,id});if(state.data)state.data.manualBookings=Array.isArray(res.bookings)?manualSort(res.bookings):(state.data.manualBookings||[]).filter(x=>x.id!==id);state.notice='면접 예약을 취소했습니다.';render();await refreshState(false);render();}catch(e){state.error=e.message;render();}finally{state.busy='';}}

async function addRoomUse(){const mode=qs('#useMode').value,teacher=qs('#useTeacher').value.trim(),subject=qs('#useSubject').value.trim();if(!teacher||!subject){state.error='교사명과 수업·사용 내용을 입력해 주세요.';return render();}const payload={token:state.token,room:qs('#useRoom').value,period:Number(qs('#usePeriod').value),label:`수업 · ${teacher} · ${subject}`};if(mode==='date')payload.dateKey=qs('#useDate').value;else payload.weekday=Number(qs('#useWeekday').value);state.busy='room-use-save';try{const res=await apiCall('addRoomUse',payload);state.notice=`특별실 사용시간을 저장했습니다.${res.sessionConflictsCleared?` 겹치던 제시문 면접 ${res.sessionConflictsCleared}건의 장소를 미정으로 변경했습니다.`:''}${res.bookingsCancelled?` 직접 예약 ${res.bookingsCancelled}건을 취소했습니다.`:''}`;state.error='';await refreshState(false);render();}catch(e){state.error=e.message;render();}finally{state.busy='';}}
async function deleteRoomUse(id){if(!confirm('이 특별실 사용시간을 삭제할까요?'))return;state.busy='room-use-delete';try{await apiCall('deleteRoomUse',{token:state.token,id});state.notice='특별실 사용시간을 삭제했습니다.';await refreshState(false);render();}catch(e){state.error=e.message;render();}finally{state.busy='';}}
