function usageInfo(dateKey,period,room){
  const use=(state.data.roomUses||[]).find(u=>roomUseMatches(u,dateKey,period,room));
  if(use)return{kind:'classuse',text:use.label};
  const sess=(state.data.sessions||[]).find(s=>dateKeyFromText(s.dateText)===dateKey&&Number(s.classPeriod)===period&&s.location===room);
  if(sess)return{kind:'session',text:`${sess.teacher} · ${(sess.students||[]).join('·')}`,session:sess};
  const booking=(state.data.manualBookings||[]).find(b=>b.dateKey===dateKey&&Number(b.period)===period&&b.room===room);
  if(booking)return{kind:'manual',text:`${booking.teacher} · ${booking.student}`,booking};
  return{kind:'free',text:'예약'};
}
function roomUseMatches(use,dateKey,period,room){ if(use.room!==room||Number(use.period)!==Number(period))return false;if(use.dateKey)return use.dateKey===dateKey;if(!use.weekday)return false;return new Date(dateKey+'T00:00:00').getDay()===Number(use.weekday); }
function roomsModal(manage){
  const date=state.modalData?.date||'2026-10-12', rooms=(state.data.roomChoices||[]).filter(r=>r!=='미정');
  const grid=`<div class="room-scroll"><div class="room-grid"><div class="room-cell head">실</div>${[1,2,3,4,5,6,7,8].map(p=>`<div class="room-cell head">${p}교시</div>`).join('')}${rooms.map(room=>`<div class="room-cell head">${esc(room)}</div>${[1,2,3,4,5,6,7,8].map(p=>{const info=usageInfo(date,p,room);return `<button class="room-cell ${info.kind}" ${['classuse','session'].includes(info.kind)?'disabled':''} data-room-cell="${esc(room)}|${p}" title="${esc(info.text)}"><strong>${info.kind==='free'?'가능':info.kind==='manual'?'예약':info.kind==='session'?'면접':'수업'}</strong>${esc(info.text)}</button>`}).join('')}`).join('')}</div></div>`;
  const manageBlock=manage?`<div class="panel" style="margin-top:14px"><div class="panel-head"><h3>특별실 사용시간 추가</h3></div><div class="field-grid"><label class="field"><span>실</span><select id="useRoom">${rooms.map(r=>`<option>${esc(r)}</option>`).join('')}</select></label><label class="field"><span>교시</span><select id="usePeriod">${[1,2,3,4,5,6,7,8].map(p=>`<option value="${p}">${p}교시</option>`).join('')}</select></label><label class="field"><span>구분</span><select id="useMode"><option value="date">특정 날짜</option><option value="weekly">매주 요일</option></select></label><label class="field"><span>날짜/요일</span><input id="useDate" type="date" value="${esc(date)}"><select id="useWeekday" class="hidden"><option value="1">월요일</option><option value="2">화요일</option><option value="3">수요일</option><option value="4">목요일</option><option value="5">금요일</option></select></label></div><label class="field"><span>수업·사용 내용</span><input id="useLabel" placeholder="예: 수업 · 홍길동 · 과목명"></label><button id="addRoomUse" class="btn primary">사용시간 추가</button><div class="table-list" style="margin-top:12px">${(state.data.roomUses||[]).slice().sort((a,b)=>a.room.localeCompare(b.room,'ko')||String(a.dateKey||'').localeCompare(String(b.dateKey||''))||Number(a.weekday||0)-Number(b.weekday||0)||Number(a.period)-Number(b.period)).map(u=>`<div class="room-use-row"><div><strong>${esc(u.room)} · ${u.period}교시</strong><div class="muted" style="font-size:12px">${esc(u.dateKey?fmtDate(u.dateKey):(['','월','화','수','목','금','토'][Number(u.weekday)]+'요일'))} · ${esc(u.label)}</div></div><button class="btn small danger" data-delete-room-use="${esc(u.id)}">삭제</button></div>`).join('')}</div></div>`:'';
  return modalWrap(`<div class="modal-head"><div><h2>${manage?'특별실 관리':'실별 사용 현황·예약'}</h2><p class="muted">빈 칸을 눌러 일반 면접 학생을 예약할 수 있습니다.</p></div><button class="btn" id="closeModal">닫기</button></div><label class="field" style="max-width:240px"><span>날짜</span><input id="roomDate" type="date" value="${esc(date)}"></label>${grid}${manageBlock}`);
}
