function renderModal(){
  if(state.auth?.mustChange||state.modal==='changePassword')return passwordModal();
  if(!state.modal)return'';
  if(state.modal==='team')return teamModal();
  if(state.modal==='materialUpload')return materialUploadModal();
  if(state.modal==='roomManage')return roomManagerModal();
  if(state.modal==='history')return historyModal();
  if(state.modal==='swap')return swapModal();
  if(state.modal==='booking')return bookingModal();
  return'';
}
function modalWrap(content,cls=''){return `<div class="modal-backdrop" id="modalBackdrop"><section class="modal ${cls}" onclick="event.stopPropagation()">${content}</section></div>`;}
function passwordModal(){return `<main class="login-shell"><section class="login-card"><p class="eyebrow login-eyebrow">학생 최초 로그인</p><h1>비밀번호 변경</h1><p class="login-help">${esc(state.auth?.name||'')} 학생은 초기 비밀번호를 개인 비밀번호로 변경해야 합니다.</p><label class="field-label">새 비밀번호<input id="newPassword" type="password" placeholder="4자 이상"></label><label class="field-label">새 비밀번호 확인<input id="newPassword2" type="password"></label>${state.error?`<div class="alert error login-error">${esc(state.error)}</div>`:''}<button id="saveNewPassword" class="login-button">변경 후 시작</button></section></main>`;}
function teamModal(){const team=state.modalData||'all';const sessions=team==='all'?sortSessions(state.data.sessions||[]):sortSessions((state.data.sessions||[]).filter(s=>s.team===team));const bookings=team==='all'?manualSort(state.data.manualBookings||[]):[];const count=sessions.length+bookings.length;return modalWrap(`<div class="team-modal-head"><div><h3>${team==='all'?'전체 일정':esc(teamLabel(team))}</h3><p>${team==='all'?'전체 면접 일정':'팀 전체 일정'} · ${count}건</p></div><button class="small-button" id="closeModal">닫기</button></div><div class="card-list team-modal-list">${sessions.map(s=>sessionCard(s,false)).join('')}${bookings.map(manualBookingCard).join('')}</div><div class="modal-actions"><button id="closeModal2">닫기</button></div>`,'team-schedule-modal');}
function materialUploadModal(){const nh=zipMaterial('humanities','usedZip'),nu=zipMaterial('natural','usedZip'),uh=zipMaterial('humanities','unusedZip'),un=zipMaterial('natural','unusedZip');return modalWrap(`<h3>면접 자료 ZIP 업로드</h3><p>자료 종류와 팀을 고른 뒤 ZIP 하나를 올리면 파일 제목을 읽어 각 일정에 자동 연결합니다.</p><label class="field-label">자료 종류<select id="materialKind"><option value="promptZip">제시문</option><option value="solutionZip">고려대 해설 포함</option><option value="unusedZip">미사용 지문 ZIP</option></select></label><label class="field-label">팀<select id="materialTeam"><option value="humanities">고려대(인문)&연세대팀</option><option value="natural">고려대(자연)팀</option></select></label><label class="field-label">ZIP 파일<input id="materialFile" type="file" accept=".zip,application/zip"></label><div id="materialProgress" class="upload-status"></div><div class="material-bar"><button class="material-button" ${nh?'data-download-material="'+esc(nh.id)+'"':'disabled'}>인문·연세 사용 지문 ZIP</button><button class="material-button" ${uh?'data-download-material="'+esc(uh.id)+'"':'disabled'}>인문·연세 미사용 ZIP</button><button class="material-button" ${nu?'data-download-material="'+esc(nu.id)+'"':'disabled'}>자연 사용 지문 ZIP</button><button class="material-button" ${un?'data-download-material="'+esc(un.id)+'"':'disabled'}>자연 미사용 ZIP</button></div><div class="modal-actions"><button id="closeModal">닫기</button><button id="uploadMaterialNow" class="primary">업로드</button></div>`);}
function historyModal(){const rows=state.data?.history||[];return modalWrap(`<div class="team-modal-head"><div><h3>변경 이력</h3><p>최근 ${rows.length}건</p></div><button class="small-button" id="closeModal">닫기</button></div><div class="history-list">${rows.length?rows.map(h=>`<div class="history-row"><strong>${esc(h.action)}</strong><span>${esc(h.actor)} · ${esc(new Date(h.createdAt).toLocaleString('ko-KR'))}</span><p>${esc(h.detail)}</p></div>`).join(''):'<div class="empty">변경 이력이 없습니다.</div>'}</div>`);}
function swapModal(){const src=(state.data.sessions||[]).find(s=>s.id===state.modalData);const targets=src?sortSessions((state.data.sessions||[]).filter(s=>s.id!==src.id&&s.team===src.team&&s.teacher!==src.teacher)):[];return modalWrap(`<h3>일정 교환</h3><p><strong>${src?esc(src.teacher):''}</strong> · ${src?esc(src.dateText):''} ${src?esc(src.period):''}</p><div class="modal-prompt">${src?esc(firstLine(src.prompt)):''}</div><label class="field-label">교환할 다른 선생님 일정<select id="swapTarget"><option value="">선택하세요</option>${targets.map(s=>`<option value="${esc(s.id)}">${esc(s.teacher+' · '+s.dateText+' '+s.period+' · '+s.group+' · '+firstLine(s.prompt))}</option>`).join('')}</select></label><div class="swap-explain"><b>시간·지문 함께 교환</b>: 서로 상대방 시간의 지문을 맡습니다.<br><b>시간만 교환</b>: 시간만 바꾸고 각자 원래 지문은 유지합니다.</div><div class="modal-actions"><button id="closeModal">취소</button><button data-swap-mode="time_only">시간만 교환</button><button class="primary" data-swap-mode="time_and_prompt">시간·지문 함께 교환</button></div>`);}
function bookingModal(){const d=state.modalData||{},b=d.booking;return modalWrap(`<h3>${b?'면접 예약':'실·교시 직접 예약'}</h3><p><strong>${esc(fmtDate(d.dateKey))} · ${d.period}교시 · ${esc(d.room)}</strong></p>${state.error?`<div class="alert error">${esc(state.error)}</div>`:''}<label class="field-label">교사<input id="bookingTeacher" value="${esc(b?.teacher||state.auth.name)}" readonly></label><label class="field-label">면접 학생<input id="bookingStudent" value="${esc(b?.student||'')}" ${b?'readonly':''} placeholder="학생 이름 직접 입력 · 일반 면접 학생도 가능" autofocus></label>${b?'':`<div class="helper-text">제시문 면접 일정에 없는 일반 면접 학생도 이름을 직접 입력할 수 있습니다.</div>`}<div class="modal-actions">${b?`<button class="danger" id="cancelBookingNow">예약 취소</button>`:''}<button id="closeModal">닫기</button>${b?'':`<button class="primary" id="saveBookingNow">시간표에 반영</button>`}</div>`,'booking-modal');}
