async function changePassword(){ const a=qs('#newPassword').value,b=qs('#newPassword2').value;if(a!==b){state.error='새 비밀번호 확인이 일치하지 않습니다.';return render();}try{await apiCall('changeStudentPassword',{token:state.token,newPassword:a});state.auth.mustChange=false;state.modal=null;state.notice='비밀번호를 변경했습니다.';await refreshState(true);}catch(e){state.error=e.message;render();} }

async function changeSession(id,patch){ try{state.error='';await apiCall('changeSession',{token:state.token,id,...patch});state.notice='일정을 변경했습니다.';await refreshState(true);}catch(e){state.error=e.message;await refreshState(true);} }
async function swapSessions(mode){const target=qs('#swapTarget')?.value;if(!target)return;try{await apiCall('swapSessions',{token:state.token,aId:state.modalData,bId:target,mode});state.modal=null;state.notice='일정 교환을 반영했습니다.';await refreshState(true);}catch(e){state.error=e.message;render();}}

async function downloadMaterial(id,play){ try{state.notice='자료를 불러오는 중입니다.';render();const res=await apiCall('downloadMaterial',{token:state.token,id},120000);const blob=base64ToBlob(res.base64,res.mimeType);state.notice='';if(play){const url=URL.createObjectURL(blob);const audio=new Audio(url);audio.controls=true;audio.autoplay=true;const w=window.open('','_blank','width=520,height=180');if(w){w.document.write(`<meta charset="utf-8"><title>${esc(res.fileName)}</title><body style="font-family:sans-serif;padding:20px"><h3>${esc(res.fileName)}</h3><audio controls autoplay style="width:100%" src="${url}"></audio></body>`);}else audio.play();setTimeout(()=>URL.revokeObjectURL(url),300000);}else downloadBlob(blob,res.fileName);render();}catch(e){state.error=e.message;state.notice='';render();} }

async function uploadReference(sessionId,file){if(file.size>20*1024*1024){state.error='참고자료는 20MB 이하로 올려 주세요.';return render();}try{state.notice='참고자료 업로드 중...';render();const base64=await blobToBase64(file);await apiCall('uploadReference',{token:state.token,sessionId,fileName:file.name,mimeType:file.type||'application/octet-stream',base64},120000);state.notice='참고자료를 업로드했습니다.';await refreshState(true);}catch(e){state.error=e.message;state.notice='';render();}}
async function deleteReference(id){if(!confirm('이 참고자료를 삭제할까요?'))return;try{await apiCall('deleteReference',{token:state.token,id});state.notice='참고자료를 삭제했습니다.';await refreshState(true);}catch(e){state.error=e.message;render();}}
async function deleteRecording(id){if(!confirm('이 녹음을 삭제할까요?'))return;try{await apiCall('deleteRecording',{token:state.token,id});state.notice='녹음을 삭제했습니다.';await refreshState(true);}catch(e){state.error=e.message;render();}}
