function apiCall(action,payload={},timeout=20000){
  const apiUrl=state.apiUrl||CONFIG.apiUrl;
  if(!apiUrl)return Promise.reject(new Error('Google Apps Script 웹앱 주소가 아직 설정되지 않았습니다.'));
  const requestId=uid();
  const body={action,requestId,origin:location.origin,...payload};
  const json=JSON.stringify(body);
  if(json.length<1800)return jsonpCall(apiUrl,body,timeout);
  return iframePostCall(apiUrl,body,timeout);
}
function jsonpCall(apiUrl,body,timeout){return new Promise((resolve,reject)=>{const callback='__yi_'+String(body.requestId).replace(/[^A-Za-z0-9_$]/g,'_');const script=document.createElement('script');let done=false;const cleanup=()=>{if(done)return;done=true;clearTimeout(timer);delete window[callback];script.remove();};window[callback]=msg=>{cleanup();msg&&msg.ok?resolve(msg.data):reject(new Error(msg?.error||'요청에 실패했습니다.'));};script.onerror=()=>{cleanup();reject(new Error('Apps Script에 연결하지 못했습니다.'));};const sep=apiUrl.includes('?')?'&':'?';script.src=`${apiUrl}${sep}callback=${encodeURIComponent(callback)}&payload=${encodeURIComponent(JSON.stringify(body))}&_=${Date.now()}`;document.head.appendChild(script);const timer=setTimeout(()=>{cleanup();reject(new Error('Apps Script 응답을 받지 못했습니다. 배포 버전을 확인해 주세요.'));},timeout);});}
function iframePostCall(apiUrl,body,timeout){return new Promise((resolve,reject)=>{const requestId=body.requestId;const iframe=document.createElement('iframe');iframe.name=`yi-api-${requestId}`;iframe.style.display='none';const form=document.createElement('form');form.method='POST';form.target=iframe.name;form.style.display='none';form.action=apiUrl;const textarea=document.createElement('textarea');textarea.name='payload';textarea.value=JSON.stringify(body);form.appendChild(textarea);document.body.append(iframe,form);let done=false;const cleanup=()=>{if(done)return;done=true;window.removeEventListener('message',onMessage);clearTimeout(timer);setTimeout(()=>{iframe.remove();form.remove();},0);};const onMessage=e=>{const msg=e.data;if(!msg||msg.requestId!==requestId)return;cleanup();msg.ok?resolve(msg.data):reject(new Error(msg.error||'요청에 실패했습니다.'));};window.addEventListener('message',onMessage);const timer=setTimeout(()=>{cleanup();reject(new Error('Apps Script 업로드 응답을 받지 못했습니다. 배포 버전과 웹앱 공개 설정을 확인해 주세요.'));},timeout);form.submit();});}
async function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=reject;r.readAsDataURL(blob);});}
function base64ToBlob(base64,mime){const bin=atob(base64);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime||'application/octet-stream'});}
function downloadBlob(blob,fileName){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fileName||'download';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
