function promptPdf(prompt){const line=firstLine(prompt).replace(/\s+/g,'_');return `${line}${line.includes('고려대')?'_문제만':''}.pdf`;}
function cleanStudentName(v){return String(v??'').replace(/\([^)]*\)/g,'').trim();}
function parseScheduleTime(value){const text=String(value??'').trim();if(!text)return null;let m=text.match(/(\d{1,2})월\s*(\d{1,2})\s*일?\s*(?:\(([^)]+)\))?\s*(오전|오후)?/);if(m){const month=+m[1],day=+m[2],key=`2026-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,d=new Date(key+'T00:00:00'),weekday=m[3]||['일','월','화','수','목','금','토'][d.getDay()];return{dateText:`${month}월 ${day}일 (${weekday})`,period:m[4]||'전체',dateKey:key};}m=text.match(/2026[-./](\d{1,2})[-./](\d{1,2})(?:\s*(오전|오후))?/);if(m){const month=+m[1],day=+m[2],key=`2026-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,d=new Date(key+'T00:00:00');return{dateText:`${month}월 ${day}일 (${['일','월','화','수','목','금','토'][d.getDay()]})`,period:m[3]||'전체',dateKey:key};}return null;}
function looksPrompt(v){const t=String(v??'').trim();return t.length>4&&(/준비\s*\d+\s*분/.test(t)||((/고려대|연세대/.test(t))&&(/전형|계열|기회균형|활동우수|고른기회/.test(t))));}
function findHeaderRow(rows){let best=-1,bestScore=-1;for(let r=0;r<Math.min(rows.length,10);r++){const vals=(rows[r]||[]).map(v=>String(v??'').trim());const teacher=vals.filter(v=>/담당\s*교사|지도\s*교사/.test(v)).length;const time=vals.filter(v=>/^(시간|날짜|일자)$/.test(v)).length;const names=vals.filter(v=>/^[가-힣]{2,5}(?:\([^)]*\))?$/.test(v)&&!/교사|시간|날짜|일자/.test(v)).length;const score=teacher*20+time*5+names;if(teacher&&score>bestScore){best=r;bestScore=score;}}return best;}
function findTeamSheet(book,team){const names=book.SheetNames||[];const exact=team==='natural'?['고려대(자연)팀']:['고려대(인문)&연세대팀','고려대(인문)&연세기균팀'];for(const n of exact)if(book.Sheets[n])return{name:n,sheet:book.Sheets[n]};const candidates=names.filter(n=>team==='natural'?(/고려대/.test(n)&&/자연/.test(n)):(/인문/.test(n)&&(/연세/.test(n)||/고려대/.test(n))));return candidates[0]?{name:candidates[0],sheet:book.Sheets[candidates[0]]}:null;}
function detectGroups(rows,headerRow){const header=(rows[headerRow]||[]).map(v=>String(v??'').trim());const teacherCols=[];header.forEach((v,i)=>{if(/담당\s*교사|지도\s*교사/.test(v))teacherCols.push(i);});if(!teacherCols.length)throw new Error('담당교사 열을 찾지 못했습니다.');const timeCol=Math.max(0,header.findIndex(v=>/^(시간|날짜|일자)$/.test(v)));const groups=[];let start=timeCol+1;teacherCols.forEach((teacherCol,index)=>{const studentCols=[];for(let c=start;c<teacherCol;c++){const name=cleanStudentName(header[c]);if(name&&!/^(\d+조|개별|시간|날짜|일자)$/.test(name))studentCols.push(c);}let group='';for(let r=Math.max(0,headerRow-3);r<=headerRow;r++){for(let c=start;c<teacherCol;c++){const v=String(rows[r]?.[c]??'').trim();if(/^\d+\s*조$/.test(v)||v==='개별'){group=v.replace(/\s+/g,'');break;}}if(group)break;}if(!group)group=(studentCols.length===1&&teacherCols.length>3&&index===teacherCols.length-1)?'개별':`${index+1}조`;groups.push({group,studentCols,teacherCol,startCol:start,endCol:teacherCol-1});start=teacherCol+1;});return{groups,timeCol};}
function parseTeamSheet(sheet,team){const rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:false,defval:null});const headerRow=findHeaderRow(rows);if(headerRow<0)throw new Error(`${teamLabel(team)} 탭에서 학생·담당교사 헤더를 찾지 못했습니다.`);const {groups,timeCol}=detectGroups(rows,headerRow);const out=[];const seen=new Set();let lastDate=null;for(let r=headerRow+1;r<rows.length;r++){const row=rows[r]||[];let time=parseScheduleTime(row[timeCol]);if(!time){for(const cell of row){time=parseScheduleTime(cell);if(time)break;}}if(time)lastDate=time;else{const periodCell=row.map(v=>String(v??'').trim()).find(v=>v==='오전'||v==='오후');if(periodCell&&lastDate)time={...lastDate,period:periodCell};else continue;}groups.forEach((g,gidx)=>{const candidates=[];for(let c=g.startCol;c<=g.endCol;c++){if(looksPrompt(row[c]))candidates.push(String(row[c]).trim());}const prompt=candidates.sort((a,b)=>b.length-a.length)[0];if(!prompt)return;const teacher=String(row[g.teacherCol]??'').trim();if(!teacher)return;const header=rows[headerRow]||[];const students=g.studentCols.map(c=>cleanStudentName(header[c])).filter(Boolean);if(!students.length)return;const periodKey=time.period==='전체'?'all':time.period;let id=`${team}-${time.dateKey.replace(/-/g,'')}-${periodKey}-g${gidx+1}`;if(seen.has(id))id+=`-r${r+1}`;seen.add(id);out.push({id,team,group:g.group,students,dateText:time.dateText,period:time.period,slotIndex:r-headerRow-1,teacher,teachers:splitTeachers(teacher),prompt,location:'미정',pdfFile:promptPdf(prompt)});});}if(!out.length)throw new Error(`${teamLabel(team)} 탭에서 면접 일정을 읽지 못했습니다.`);return out;}
function parseWorkbook(book){const natural=findTeamSheet(book,'natural'),humanities=findTeamSheet(book,'humanities');if(!natural||!humanities)throw new Error('자연팀과 인문·연세대팀 일정 탭을 모두 찾지 못했습니다.');const n=parseTeamSheet(natural.sheet,'natural'),h=parseTeamSheet(humanities.sheet,'humanities');const duplicate=new Set(),dup=[];[...n,...h].forEach(s=>{const key=[s.team,s.dateText,s.period,s.group,(s.students||[]).join('|')].join('::');if(duplicate.has(key))dup.push(key);duplicate.add(key);});if(dup.length)throw new Error('같은 팀·날짜·조 일정이 중복되어 있습니다. 엑셀 내용을 확인해 주세요.');return[...n,...h];}
async function uploadScheduleFile(file){try{state.notice='일정 엑셀을 읽는 중입니다.';state.error='';render();const book=XLSX.read(await file.arrayBuffer(),{type:'array'});const sessions=parseWorkbook(book);const n=sessions.filter(s=>s.team==='natural').length,h=sessions.filter(s=>s.team==='humanities').length;state.notice=`자연 ${n}건 + 인문·연세 ${h}건 = 총 ${sessions.length}건을 서버에 반영하는 중입니다.`;render();const res=await apiCall('uploadSchedule',{token:state.token,sessions},120000);state.notice=`업로드 완료 · 자연 ${n}건 + 인문·연세 ${h}건 = 총 ${res.count}건`;await refreshState(true);}catch(e){state.error=e.message;state.notice='';render();}}

setInterval(()=>{if(state.token&&state.auth&&!Object.values(state.recorder).some(r=>['recording','paused'].includes(r.status))){refreshState(false).then(()=>{if(!state.modal)render();}).catch(()=>{});}},CONFIG.pollMs||8000);

(async function boot(){if(!state.apiUrl&&!CONFIG.apiUrl){renderSetup();return;}if(state.token){try{await refreshState(false);if(state.data){render();return;}}catch(e){}}renderLogin();})();
