function renderModal(){
  if(state.auth?.mustChange || state.modal==='changePassword') return passwordModal();
  if(!state.modal)return'';
  if(state.modal==='team')return teamModal();
  if(state.modal==='materialUpload')return materialUploadModal();
  if(state.modal==='rooms')return roomsModal(false);
  if(state.modal==='roomManage')return roomsModal(true);
  if(state.modal==='history')return historyModal();
  if(state.modal==='swap')return swapModal();
  return'';
}
function modalWrap(content,cls=''){return `<div class="modal-backdrop" id="modalBackdrop"><section class="modal ${cls}" onclick="event.stopPropagation()">${content}</section></div>`;}
function passwordModal(){return modalWrap(`<div class="modal-head"><div><h2>학생 최초 로그인</h2><p class="muted">초기 비밀번호 1234를 개인 비밀번호로 변경합니다.</p></div></div><label class="field"><span>새 비밀번호</span><input id="newPassword" type="password" placeholder="4자 이상"></label><label class="field"><span>새 비밀번호 확인</span><input id="newPassword2" type="password"></label><button id="saveNewPassword" class="btn primary" style="width:100%">변경 후 시작</button>`,'narrow');}
function teamModal(){ const team=state.modalData||'all';const items=team==='all'?sortSessions(state.data.sessions):sortSessions(state.data.sessions.filter(s=>s.team===team));return modalWrap(`<div class="modal-head"><div><h2>${team==='all'?'전체 일정':esc(teamLabel(team))}</h2><span class="muted">${items.length}건</span></div><button class="btn" id="closeModal">닫기</button></div><div class="cards">${items.map(sessionCard).join('')}</div>`);}
function materialUploadModal(){return modalWrap(`<div class="modal-head"><div><h2>면접 자료 ZIP 업로드</h2><p class="muted">사용 지문 ZIP은 각 일정의 PDF와 자동 연결됩니다.</p></div><button class="btn" id="closeModal">닫기</button></div><div class="field-grid"><label class="field"><span>자료 종류</span><select id="materialKind"><option value="promptZip">사용 제시문 ZIP</option><option value="solutionZip">고려대 해설 포함 ZIP</option><option value="unusedZip">미사용 지문 ZIP</option></select></label><label class="field"><span>팀</span><select id="materialTeam"><option value="humanities">고려대(인문)&연세대팀</option><option value="natural">고려대(자연)팀</option></select></label></div><label class="field"><span>ZIP 파일</span><input id="materialFile" type="file" accept=".zip,application/zip"></label><button id="uploadMaterialNow" class="btn primary">업로드</button><div id="materialProgress" class="progress"></div>`,'narrow');}
function historyModal(){ const rows=state.data?.history||[];return modalWrap(`<div class="modal-head"><div><h2>변경 이력</h2><span class="muted">최근 ${rows.length}건</span></div><button class="btn" id="closeModal">닫기</button></div>${rows.length?rows.map(h=>`<div class="history-row"><strong>${esc(h.action)}</strong><small>${esc(h.actor)} · ${esc(new Date(h.createdAt).toLocaleString('ko-KR'))}</small><div>${esc(h.detail)}</div></div>`).join(''):'<div class="empty">변경 이력이 없습니다.</div>'}`);}
function swapModal(){ const src=state.data.sessions.find(s=>s.id===state.modalData); const targets=src?sortSessions(state.data.sessions.filter(s=>s.id!==src.id&&s.team===src.team&&s.teacher!==src.teacher)):[];return modalWrap(`<div class="modal-head"><div><h2>일정 교환</h2><p class="muted">${src?esc(src.teacher+' · '+src.dateText+' · '+firstLine(src.prompt)):''}</p></div><button class="btn" id="closeModal">닫기</button></div><label class="field"><span>교환할 일정</span><select id="swapTarget"><option value="">선택하세요</option>${targets.map(s=>`<option value="${esc(s.id)}">${esc(s.teacher+' · '+s.dateText+' · '+s.group+' · '+firstLine(s.prompt))}</option>`).join('')}</select></label><div class="toolbar"><button class="btn" data-swap-mode="time_only">시간만 교환</button><button class="btn primary" data-swap-mode="time_and_prompt">시간·지문 함께 교환</button></div>`,'narrow');}
