async function startRecording(sessionId){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];const media=new MediaRecorder(stream);const rec={media,stream,chunks,status:'recording',blob:null,url:''};state.recorder[sessionId]=rec;media.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data);};media.onstop=()=>{rec.blob=new Blob(chunks,{type:media.mimeType||'audio/webm'});rec.url=URL.createObjectURL(rec.blob);rec.status='ready';stream.getTracks().forEach(t=>t.stop());render();};media.start(1000);render();}catch(e){state.error='마이크를 사용할 수 없습니다. 브라우저의 마이크 권한을 확인해 주세요.';render();}}
function pauseRecording(id){const r=state.recorder[id];if(r?.media?.state==='recording'){r.media.pause();r.status='paused';render();}}
function resumeRecording(id){const r=state.recorder[id];if(r?.media?.state==='paused'){r.media.resume();r.status='recording';render();}}
function stopRecording(id){const r=state.recorder[id];if(r?.media&&r.media.state!=='inactive')r.media.stop();}
function resetRecording(id){const r=state.recorder[id];if(r?.url)URL.revokeObjectURL(r.url);delete state.recorder[id];render();}
async function uploadRecording(id){const r=state.recorder[id];if(!r?.blob)return;try{state.notice='녹음을 업로드하는 중입니다.';render();const base64=await blobToBase64(r.blob);const ext=r.blob.type.includes('ogg')?'ogg':r.blob.type.includes('mp4')?'m4a':'webm';await apiCall('uploadRecording',{token:state.token,sessionId:id,fileName:`${state.auth.name}_${dateKeyFromText(state.data.sessions.find(s=>s.id===id)?.dateText||'')}.${ext}`,mimeType:r.blob.type||'audio/webm',base64},120000);resetRecording(id);state.notice='녹음을 업로드했습니다. 담당 교사 화면에 곧 표시됩니다.';await refreshState(true);}catch(e){state.error=e.message;state.notice='';render();}}

async function uploadMaterialZip(){const kind=qs('#materialKind').value,team=qs('#materialTeam').value,file=qs('#materialFile').files?.[0];if(!file)return;if(file.size>30*1024*1024){qs('#materialProgress').textContent='ZIP 파일은 30MB 이하로 올려 주세요.';return;}try{qs('#uploadMaterialNow').disabled=true;qs('#materialProgress').textContent='파일 읽는 중...';const base64=await blobToBase64(file);qs('#materialProgress').textContent='Google Drive에 업로드 중...';const res=await apiCall('uploadMaterialZip',{token:state.token,kind,team,fileName:file.name,base64},150000);qs('#materialProgress').textContent=`업로드 완료${res.pdfCount?` · PDF ${res.pdfCount}개`:''}`;state.notice='면접 자료를 업로드했습니다.';await refreshState(false);setTimeout(()=>{state.modal=null;render();},600);}catch(e){qs('#materialProgress').textContent=e.message;}finally{if(qs('#uploadMaterialNow'))qs('#uploadMaterialNow').disabled=false;}}

async function roomCellAction(btn){const [room,p]=btn.dataset.roomCell.split('|'),period=Number(p),date=state.modalData?.date||'2026-10-12',info=usageInfo(date,period,room);if(info.kind==='free'){const student=prompt(`${fmtDate(date)} ${period}교시 ${room}\n면접 학생 이름을 입력하세요.`);if(!student)return;try{await apiCall('createManualBooking',{token:state.token,dateKey:date,period,room,student:student.trim()});state.notice='면접실을 예약했습니다.';await refreshState(false);render();}catch(e){state.error=e.message;render();}}else if(info.kind==='manual'){if(!confirm(`${info.text}\n이 직접 예약을 취소할까요?`))return;try{await apiCall('cancelManualBooking',{token:state.token,id:info.booking.id});state.notice='예약을 취소했습니다.';await refreshState(false);render();}catch(e){state.error=e.message;render();}}}
async function addRoomUse(){const mode=qs('#useMode').value,payload={token:state.token,room:qs('#useRoom').value,period:Number(qs('#usePeriod').value),label:qs('#useLabel').value.trim()};if(mode==='date')payload.dateKey=qs('#useDate').value;else payload.weekday=Number(qs('#useWeekday').value);try{const res=await apiCall('addRoomUse',payload);state.notice=`특별실 사용시간을 추가했습니다.${res.sessionConflictsCleared?` 면접 ${res.sessionConflictsCleared}건의 장소를 미정으로 변경했습니다.`:''}`;await refreshState(false);render();}catch(e){state.error=e.message;render();}}
async function deleteRoomUse(id){if(!confirm('이 특별실 사용시간을 삭제할까요?'))return;try{await apiCall('deleteRoomUse',{token:state.token,id});state.notice='특별실 사용시간을 삭제했습니다.';await refreshState(false);render();}catch(e){state.error=e.message;render();}}
