const SUBJECTS=['화법과 작문','언어와 매체','확률과 통계','미적분','기하','수학Ⅰ','수학Ⅱ','수학I','수학II','국어','문학','독서','수학','영어','한국사','통합사회','통합과학','사회문화','생활과 윤리','윤리와 사상','정치와 법','경제','세계지리','한국지리','동아시아사','세계사','물리학','화학','생명과학','지구과학','정보','인공지능','과학탐구실험','실용영어','심화국어','체육','음악','미술','한문','기술가정'];
const ACTIVITY_WORDS=['탐구','실험','분석','조사','제작','발표','토론','프로젝트','연구','작성','설계','참여','수행','읽고','비교','제안','기획','운영','협력','봉사','문제 해결','개선','모형','캠페인'];
function sectionFromLine(line){if(/진로활동/.test(line))return'진로활동';if(/자율활동/.test(line))return'자율활동';if(/동아리활동/.test(line))return'동아리활동';if(/행동특성|종합의견/.test(line))return'행동특성';if(/세부능력.*특기사항|교과세특|세특/.test(line))return'교과세특';return'';}
function subjectFromLine(line){return SUBJECTS.find(s=>line.includes(s))||'';}
function scoreOnly(line){const hasActivity=ACTIVITY_WORDS.some(w=>line.includes(w));if(hasActivity)return false;if(/원점수|과목평균|표준편차|성취도|석차등급|수강자수|이수단위|학점|등급/.test(line))return true;const letters=(line.match(/[가-힣A-Za-z]/g)||[]).length,nums=(line.match(/\d/g)||[]).length;return nums>6&&nums>letters;}
function splitSentences(line){return String(line||'').split(/(?<=[.!?])\s+|(?<=함)\s+(?=[가-힣A-Z])|(?<=임)\s+(?=[가-힣A-Z])/).map(x=>x.trim()).filter(Boolean);}
function classifyRecord(item){const s=item.text;if(item.section==='진로활동'||/진로|전공|학과|직업|희망|진학|전문가/.test(s))return'career';if(item.section==='동아리활동'||item.section==='자율활동'||/협력|갈등|배려|리더십|공동체|소통|봉사|역할|기여|학급/.test(s))return'community';return'academic';}
function recordItems(text){const lines=String(text||'').replace(/\r/g,'\n').split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);let grade='',section='',subject='';const out=[],seen=new Set();for(const line of lines){const gm=line.match(/(?:^|\s)([123])학년(?:\s|$|[가-힣])/);if(gm)grade=gm[1]+'학년';const sec=sectionFromLine(line);if(sec)section=sec;const sub=subjectFromLine(line);if(sub)subject=sub;if(scoreOnly(line))continue;for(let sentence of splitSentences(line)){sentence=sentence.replace(/^(?:[123]학년\s*)/,'').replace(/^(?:세부능력 및 특기사항|교과세특|진로활동|자율활동|동아리활동)\s*[:：-]?/,'').trim();if(sentence.length<28||sentence.length>360)continue;if(!ACTIVITY_WORDS.some(w=>sentence.includes(w))&&!/느낀|배운|해결|주도|도출|제시|설명|의견/.test(sentence))continue;const key=norm(sentence);if(seen.has(key))continue;seen.add(key);const item={text:sentence,grade,section,subject};item.category=classifyRecord(item);out.push(item);}}return out.slice(0,500);}
function recordLocation(item){const bits=[];if(item.grade)bits.push(item.grade);if(item.section)bits.push(item.section);const base=bits.join(' ');if(item.section==='교과세특'&&item.subject)return`${base||'교과세특'}의 ${item.subject} 교과`;if(item.subject&&!item.section)return`${base?base+' ':''}${item.subject} 교과`;return base||'생활기록부';}
function quoteText(text,limit=105){let s=String(text||'').replace(/\s+/g,' ').trim();if(s.length>limit)s=s.slice(0,limit).replace(/\s+\S*$/,'')+'…';return s;}
function activityPhrase(text){const s=String(text||'').replace(/\s+/g,' ').trim();for(const w of['실험','탐구','분석','조사','프로젝트','제작','발표','토론','연구','캠페인','설계']){const i=s.indexOf(w);if(i>=0){let pre=s.slice(Math.max(0,i-32),i).split(/[,.·;:]/).pop().trim();pre=pre.replace(/^(통해|관해|대한|관련한|주제로|에서|수업에서)\s*/,'').trim();if(pre.length>2)return`${pre} ${w}`.trim();return w;}}return'활동';}
function topRecordItems(items,category,count=7){return items.filter(x=>x.category===category).map((x,i)=>{const kw=(KEY[category]||[]).filter(k=>x.text.includes(k)).length;const verb=ACTIVITY_WORDS.filter(k=>x.text.includes(k)).length;return{x,score:kw*5+verb*4+Math.min(x.text.length,180)/90-i/1000};}).sort((a,b)=>b.score-a.score).slice(0,count).map(x=>x.x);}
function pastPool(sel){let rows=STATE.questions.filter(q=>univNorm(q.u)===univNorm(sel.u));const known=rows.filter(q=>questionType(q)===sel.type);if(known.length>=6)rows=known;if(sel.dept!==ALL_DEPT&&sel.dept!==UNKNOWN_DEPT){const exact=rows.filter(q=>cleanDept(q.d)===sel.dept||cleanDept(q.d)===UNKNOWN_DEPT);if(exact.length>=4)rows=exact;}if(rows.length<8&&sel.dept!==ALL_DEPT){const grp=deptGroup(sel.dept);const similar=STATE.questions.filter(q=>questionType(q)===sel.type&&grp!=='기타'&&deptGroup(q.d)===grp);rows=[...rows,...similar];}return rows;}
function qCategory(q){const s=q.q;const scores={academic:(KEY.academic||[]).filter(w=>s.includes(w)).length,career:(KEY.career||[]).filter(w=>s.includes(w)).length,community:(KEY.community||[]).filter(w=>s.includes(w)).length};return Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][1]?Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0]:'academic';}
function referenceFor(item,category,sel,used=new Set()){const ls=new Set(tokenize(item.text)),pool=pastPool(sel);let best=null,bestScore=-Infinity,bestIndex=-1;for(const q of pool){const qi=q._i;if(used.has(qi))continue;let score=0;if(univNorm(q.u)===univNorm(sel.u))score+=80;const d=cleanDept(q.d);if(sel.dept!==ALL_DEPT&&d===sel.dept)score+=45;else if(sel.dept!==ALL_DEPT&&d===UNKNOWN_DEPT)score+=20;if(questionType(q)===sel.type)score+=24;if(qCategory(q)===category)score+=16;let overlap=0;for(const t of(STATE.qTokens[qi]||tokenize(q.q)))if(ls.has(t))overlap++;score+=overlap*7;if(q.k==='대학공개'||q.k==='대학기출')score+=8;if(score>bestScore){bestScore=score;best=q;bestIndex=qi;}}if(bestIndex>=0)used.add(bestIndex);return best;}
function tailorQuestion(category,item,dept,ref){const loc=recordLocation(item),quote=quoteText(item.text),topic=activityPhrase(item.text),r=ref?.q||'';const intro=`생활기록부 ${loc}에 “${quote}”라고 되어 있는데요. `;if(category==='academic'){if(/실험/.test(item.text))return intro+`여기서 한 ${topic}에서 본인이 직접 설계하거나 수행한 과정, 결과, 그리고 결과를 어떻게 해석했는지 설명해 주세요.`;if(/분석/.test(item.text))return intro+`여기서 ${topic}을 어떤 기준과 근거로 분석했는지 구체적으로 설명해 주세요.`;if(/탐구|연구/.test(item.text))return intro+`${topic}를 시작한 이유와 실제 탐구 과정, 그리고 본인이 내린 결론을 설명해 주세요.`;if(/조사/.test(item.text))return intro+`${topic}에서 어떤 자료를 어떤 기준으로 조사했고, 그 결과 무엇을 확인했는지 설명해 주세요.`;if(/제작|설계|프로젝트/.test(item.text))return intro+`${topic}를 진행할 때 본인이 맡은 부분과 가장 어려웠던 점, 그것을 해결한 과정을 설명해 주세요.`;if(/왜|이유/.test(r))return intro+`이 활동을 하게 된 이유와 활동 중 가장 중요하게 판단한 점을 설명해 주세요.`;return intro+`여기서 한 ${topic}에 대해 본인이 실제로 한 일을 중심으로 구체적으로 설명해 주세요.`;}if(category==='career'){if(/분석/.test(item.text))return intro+`이 활동에서 무엇을 어떤 관점으로 분석했고, 그 분석이 ${dept===ALL_DEPT?'지원 전공':dept}에 대한 관심과 어떻게 이어졌는지 설명해 주세요.`;if(/실험|탐구|연구/.test(item.text))return intro+`${topic}에서 가장 깊게 확인한 내용이 무엇이고, 이것이 진로 선택에 어떤 영향을 주었는지 설명해 주세요.`;if(/지원|동기|이유/.test(r))return intro+`이 경험이 ${dept===ALL_DEPT?'지원 전공':dept}에 지원하게 된 계기와 어떻게 연결되는지 설명해 주세요.`;return intro+`${topic}를 하면서 진로에 대해 새롭게 알게 된 점과 이후 더 확인한 내용을 설명해 주세요.`;}if(/협력|팀|조별|공동/.test(item.text))return intro+`${topic}에서 본인이 맡은 역할과 다른 구성원들과 협력한 방식을 구체적으로 설명해 주세요.`;if(/갈등|의견|조정/.test(item.text)||/갈등|의견|소통/.test(r))return intro+`활동 중 의견이 달랐던 상황이 있었다면 어떤 방식으로 조정했고 결과가 어땠는지 설명해 주세요.`;if(/봉사|배려/.test(item.text))return intro+`이 활동에서 상대방의 입장을 고려해 실제로 한 행동과 그 결과를 설명해 주세요.`;return intro+`${topic}에서 본인이 맡은 역할, 실제로 기여한 부분, 그리고 그 과정에서 배운 점을 설명해 주세요.`;}
function commonQuestionsForGeneration(sel){const rows=STATE.common.length?STATE.common:FALLBACK_COMMON;return rows.slice(0,4).map(x=>({question:x.q.replace(/우리 대학/g,sel.u).replace(/이 학과/g,sel.dept===ALL_DEPT?'지원 학과':sel.dept),why:STATE.common.length?`선생님이 등록한 공통질문 · ${x.category||'공통'}`:'기본 공통질문',ref:null}));}
function generateQuestions(){const sel={...STATE.selection},items=recordItems(STATE.recordText),used=new Set();const result={common:commonQuestionsForGeneration(sel),academic:[],career:[],community:[],selection:sel};for(const category of['academic','career','community']){let chosen=topRecordItems(items,category,8);if(chosen.length<4)chosen=[...chosen,...items.filter(x=>!chosen.includes(x)).slice(0,4-chosen.length)];for(const item of chosen.slice(0,4)){const ref=referenceFor(item,category,sel,used);result[category].push({question:tailorQuestion(category,item,sel.dept,ref),why:`생활기록부 근거 · ${recordLocation(item)}: ${quoteText(item.text,120)}`,ref});}}return result;}
function refHtml(ref){if(!ref)return'';const[label,cls]=sourceLabel(ref.k);return`<div class="why"><b>가까운 실제 질문</b> · <span class="badge ${cls}">${esc(label)}</span> ${esc(ref.u)} · ${esc(cleanDept(ref.d))}${ref.y?' · '+esc(ref.y)+'학년도':''}<br>${esc(ref.q)}</div>`;}
function generatedHtml(g){const cats=[['common','공통질문'],['academic','학업역량'],['career','진로역량'],['community','공동체역량']];return`<div class="panel"><h2>${esc(g.selection.u)} · ${esc(g.selection.dept)} 맞춤 면접</h2></div>${cats.map(([key,title])=>`<section class="category"><h2>${title}<span>${g[key].length}문항</span></h2><div class="qcards">${g[key].map((x,i)=>`<article class="qcard"><div class="source"><span class="badge generated">맞춤 생성</span><span class="badge">${title}</span></div><p class="q">Q${i+1}. ${esc(x.question)}</p><div class="why">${esc(x.why)}</div>${refHtml(x.ref)}</article>`).join('')}</div></section>`).join('')}`;}
function typeMatches(q,type){const qt=questionType(q);return!qt||qt===type;}
function universityDeptSearch(q,query){const n=norm(query);if(!n)return true;return norm(`${q.u} ${cleanDept(q.d)}`).includes(n);}
function pastRows(){const sel=STATE.selection;let rows=STATE.questions.slice();const hasSearch=STATE.pastSearch.trim().length>0;if(hasSearch)rows=rows.filter(q=>universityDeptSearch(q,STATE.pastSearch));else{rows=rows.filter(q=>univNorm(q.u)===univNorm(sel.u));if(sel.dept!==ALL_DEPT)rows=rows.filter(q=>cleanDept(q.d)===sel.dept||cleanDept(q.d)===UNKNOWN_DEPT);}rows=rows.filter(q=>typeMatches(q,sel.type));if(!STATE.includeReviews)rows=rows.filter(q=>q.k!=='후기·기출');return rows.sort((a,b)=>Number(b.y||0)-Number(a.y||0)||(a.k==='후기·기출')-(b.k==='후기·기출'));}
function pastCard(q){const[label,cls]=sourceLabel(q.k),qt=questionType(q);return`<article class="past"><div class="source"><span class="badge ${cls}">${esc(label)}</span><span class="badge">${esc(q.y?q.y+'학년도':'연도 미상')}</span><span class="badge">${esc(cleanDept(q.d))}</span>${qt?`<span class="badge">${esc(qt)}</span>`:''}</div><p>${esc(q.q)}</p><small>${esc(q.s.join(' · ')||'출처 미상')}${q.n>1?' · 동일 문항 '+q.n+'회 확인':''}</small></article>`;}
function renderPast(){const rows=pastRows();$('#app').innerHTML=`<section class="page">${pageHead('대학별 기출')}<div class="panel">${selectorHtml(STATE.selection,true)}<div class="search"><b>대학·학과 검색</b><input id="pastSearch" value="${esc(STATE.pastSearch)}" placeholder="예: 연세대 경영 / 중앙대 화학 / 건국대 미디어"></div><label class="check"><input id="includeReviews" type="checkbox" ${STATE.includeReviews?'checked':''}>면접 후기 포함</label></div><div class="resultbar"><b>${STATE.pastSearch?`검색 결과 ${rows.length.toLocaleString()}문항`:`${esc(STATE.selection.u)} ${rows.length.toLocaleString()}문항`}</b><span>대학·학과·모집단위를 기준으로 찾습니다.</span></div><div class="pastlist">${rows.slice(0,STATE.pastLimit).map(pastCard).join('')||'<div class="empty">현재 조건에서 확인되는 면접 질문이 없습니다.</div>'}</div>${rows.length>STATE.pastLimit?`<button id="morePast" class="primary">더 보기 (${Math.min(200,rows.length-STATE.pastLimit)}문항)</button>`:''}</section>`;bindSelectors($('#app'),()=>{STATE.pastLimit=150;renderPast();});$('#pastSearch').oninput=e=>{STATE.pastSearch=e.target.value;STATE.pastLimit=150;renderPast();};$('#includeReviews').onchange=e=>{STATE.includeReviews=e.target.checked;STATE.pastLimit=150;renderPast();};if($('#morePast'))$('#morePast').onclick=()=>{STATE.pastLimit+=200;renderPast();};}
function commonRows(){return STATE.common.length?STATE.common:FALLBACK_COMMON;}
function renderCommon(){const custom=STATE.common.length>0,rows=commonRows();$('#app').innerHTML=`<section class="page">${pageHead('공통질문','선생님이 작성한 공통질문 파일을 불러와 사용할 수 있습니다.')}<div class="panel"><div class="commonToolbar"><div><h2>공통질문 파일</h2><p class="muted">${custom?`현재 이 브라우저에 ${STATE.common.length}문항이 저장되어 있습니다.`:'아직 선생님 공통질문 파일이 등록되지 않아 기본 4문항을 표시합니다.'}</p></div>${custom?'<button id="clearCommon" class="danger tiny">등록 질문 지우기</button>':''}</div><label class="filebox" id="commonDrop"><input id="commonFile" type="file" accept=".hwpx,.pdf,.txt,text/plain,application/pdf"><b>공통질문 파일 선택 또는 여기에 드래그</b><span>HWPX · PDF · TXT 지원 / 구형 HWP는 HWPX로 다시 저장해 주세요.</span></label><div id="commonStatus"></div></div><div class="resultbar"><b>${rows.length}문항</b><span>${custom?'선생님 등록 공통질문':'기본 공통질문'}</span></div><div class="commonList">${rows.map((x,i)=>`<article><small>${esc(x.category||'공통')}</small><p>${i+1}. ${esc(x.q)}</p></article>`).join('')}</div></section>`;$('#commonFile').onchange=e=>handleCommonFile(e.target.files[0]);const drop=$('#commonDrop');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag');}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag');}));drop.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)handleCommonFile(f);});if($('#clearCommon'))$('#clearCommon').onclick=()=>{localStorage.removeItem('yanggok_common_questions_v1');STATE.common=[];renderCommon();};}
async function handleCommonFile(file){if(!file)return;const status=$('#commonStatus');status.innerHTML='<div class="muted">질문을 추출하는 중입니다.</div>';try{const text=await readDocument(file),rows=parseCommonQuestions(text);if(!rows.length)throw new Error('질문 문장을 찾지 못했습니다.');saveCommon(rows);renderCommon();}catch(e){status.innerHTML=`<div class="error">${esc(e.message||e)}</div>`;}}
function parseCommonQuestions(text){const lines=String(text||'').replace(/\r/g,'\n').split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);let cat='공통',out=[],seen=new Set();const questionLike=/(\?|무엇|어떤|어떻게|왜|설명해|말해|이야기해|생각합니까|생각하나요|입니까|나요|까요|습니까|하세요|해 보세요|해보세요)/;for(let line of lines){if(line.length<=28&&!questionLike.test(line)&&!/^\d+[.)]/.test(line)){cat=line.replace(/[:：]$/,'');continue;}line=line.replace(/^[\s□■●○•\-–—]+/,'').replace(/^\d+\s*[.)]\s*/,'').trim();for(let q of line.split(/(?<=\?)\s+(?=\d*[.)]?\s*[가-힣A-Z])/)){q=q.trim();if(q.length<8||!questionLike.test(q))continue;const key=norm(q);if(seen.has(key))continue;seen.add(key);out.push({category:cat||'공통',q});}}return out.slice(0,300);}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){STATE.tab=tab.dataset.tab;render();}const home=e.target.closest('[data-go="home"]');if(home){STATE.tab='home';render();}});
loadData().then(render).catch(e=>{$('#app').innerHTML=`<section class="page"><div class="error"><b>기출 자료를 불러오지 못했습니다.</b><br>${esc(e.message||e)}</div></section>`;});
